### ISSUE TITLE
Only deploys first script

### ISSUE THREAD

**Issue by jasonbyrne** [stackpath/edgeengine-cli#13]
When I have more than one script in my edgeengine.json it just deploys whichever one is first. If I flip their order in the edgeengine.json it will deploy the other!

**Comment by klaude** [comment]
Howdy! Can you paste console output when run with the `-v` flag? Please censor out any sensitive information from the output. Verbose logging may help point out the cause. Thanks!

**Comment by jasonbyrne** [comment]
We went through all this for a couple of hours on Slack this morning.
Supposedly this issue has to do with the size of my scripts being over 1MB.
I await word of a fix. For now it doesn't work.

**Comment by klaude** [comment]
In that case #17 may have fixed the issue. Can you pull the latest master branch and try again? If it looks good we'll tag a new release.

**Comment by jasonbyrne** [comment]
I don't think the new update is on npm so I can't test.

**Comment by klaude** [comment]
@TLadd cut version 1.0.2. Give it a try and let us know how it looks. Thanks!
